config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :new, :create]
  root 'users#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
    @user.project.build
  end

  def create
    _project = params[:user][:projects].first.last
    _project.each do |project|
      (@user.project << Project.find_by(name: project)) if project.present?
      @user.update_attributes(:project_description => params[:user][:project_description])
    end
    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'User was successfully created.' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user =  params[:id].present? ?  User.find(params[:id]) : User.find_by(name: user_params[:name])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, projects_attributes: [:id, :name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  #Fetch All User From User Table
  def fetch_all_user
    User.all.map(&:name)
  end

  #Fetch All Project From Project Table
  def fetch_all_project
    Project.all.map(&:name)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InficareTask</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults, 'nested_form' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Inficare Task', users_path, class: 'navbar-brand' %>
    </div>
  </div>
</nav>

<div class="container">
  <div class="starter-template">
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
    <div class='panel panel-default'>
      <div class='panel-heading txt_align_lft'>Assign User With Project</div>
      <div class='panel-body'>
        <div id='display_error' class='alert alert-danger collapse'></div>
        <div class='clear_with_height'></div>
        <div class='col-xs-10' id='nested_fields'>
          <%= f.input :name, as: :select, collection: fetch_all_user, prompt: 'Select User',
                      input_html: {class: 'form-control col-xs-5'}, label: 'User Name' %>
          <div class='clear_with_height'></div>
          <%= f.simple_fields_for :projects do |project_form| %>
              <%= project_form.input :name, as: :select, collection: fetch_all_project, label: 'Select Project',
                                     include_blank: false, input_html: {multiple: true, class: 'form-control col-xs-5'}
              %>
              <div class='clear_with_height_5'></div>
              <span class='label label-default mrgn_rgt_36'>You can also select multiple project for same user.</span>
          <% end %>
          <div class='clear_with_height'></div>
          <%= f.input :project_description, as: :text, label: 'Project  Description',
                      input_html: {class: 'form-control col-xs-5 resize_none'} %><br>
          <div class='clear_with_height'></div>
          <div class='col-xs-5 mrgn_lft_16'>
            <%= f.submit class: 'btn btn-primary pull-left', id: 'assign_project', value: 'Assign Project' %>
            <%= link_to 'Back', users_path, class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    </div>
<% end %>

<script>
  $('#assign_project').click(function(){
     if ($('#user_name :selected').val() == ''){
         $('#display_error').show().html('Please Select User Name and Project');
         return false;
     }
  });
</script>

app/views/users/index.html.erb
<div class='alert dash_board'>User Project Dashboard</div>
<table class='table table-bordered table-responsive'>
  <thead>
    <tr>
      <th><%= label_tag :user_name, 'User Name'%></th>
      <th><%= label_tag :user_project, 'User Projects'%></th>
      <th><%= label_tag :project_description, 'Project Description'%></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <% if user.project.present? %>
      <tr>
        <td><%= user.name %></td>
        <td>
          <% user.project.each do |proj|  %>
            <%= proj.name %>
          <% end %>
        </td>
        <td><%= user.project_description %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
<div class='clear_with_height'></div>
<%= link_to 'Assign Project', new_user_path, class: 'btn btn-primary' %>

app/views/users/new.html.erb
<%= render 'form' %>